call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-fugitive'
Plug 'sickill/vim-monokai'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/syntastic'
Plug 'mhinz/vim-signify'
Plug 'valloric/youcompleteme'
Plug 'hashivim/vim-packer'
Plug 'hashivim/vim-terraform'
Plug 'dietsche/vim-lastplace'
Plug 'pearofducks/ansible-vim'
Plug 'fatih/vim-go'
Plug 'godlygeek/tabular'

call plug#end()

set nocompatible
set t_Co=256
syntax enable
syntax on
filetype plugin indent on

set autoindent
set autowrite " Automatically save before commands like :next and :make
set cindent
set copyindent
set expandtab
set formatoptions=jcroql
set hidden " Hide buffers when they are abandoned
set history=1000
set hlsearch " highlight results of a search
set ignorecase
set ignorecase " Do case insensitive matching
set incsearch " Incremental search
set laststatus=2
set listchars+=extends:>
set listchars+=precedes:<
set number " linenumber
set ruler
set scrolloff=4 " Keep 4 lines above and below cursor
set shiftround
set shiftwidth=2 " By default 4 indent spaces
set showcmd " Show (partial) command in status line.
set showmatch " Show matching brackets.
set smartcase
set smartcase " Do smart case matching
set smarttab
set tabstop=2 " By default 4 indent spaces
set title
set wrapscan

" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1

" Use compact syntax for prettified multi-line comments
let g:NERDCompactSexyComs = 1

" Align line-wise comment delimiters flush left instead of following code  indentation
let g:NERDDefaultAlign = 'left'

" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1" Enable trimming of trailing whitespace

" Last Place ignore git files
let g:lastplace_ignore = "gitcommit,gitrebase"

" ansible config

let g:ansible_extra_syntaxes = "sh.vim"

let g:ansible_attribute_highlight = "a"

let g:ansible_name_highlight = 'd'

let g:ansible_extra_keywords_highlight = 1



" TODO do some fugitive config

syntax enable
colorscheme monokai
hi Normal       ctermfg=252   ctermbg=none
hi CursorLine   ctermbg=234   cterm=none
hi CursorLineNr ctermfg=208   cterm=none


filetype plugin on
set omnifunc=syntaxcomplete#Complete

"Avoid enter in Replace mode from a double <Insert>
imap <Insert> <Nop>

"Enforce Python interpreter
let g:ycm_server_python_interpreter = "/usr/bin/python"
