call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-fugitive'
Plug 'sickill/vim-monokai'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/syntastic'
Plug 'mhinz/vim-signify'
Plug 'valloric/youcompleteme'
Plug 'hashivim/vim-packer'
Plug 'hashivim/vim-terraform'

call plug#end()

set nocompatible
syntax enable
syntax on
filetype plugin indent on

set showcmd " Show (partial) command in status line.
set showmatch " Show matching brackets.
set ignorecase " Do case insensitive matching
set smartcase " Do smart case matching
set incsearch " Incremental search
set autowrite " Automatically save before commands like :next and :make
set hidden " Hide buffers when they are abandoned
set history=1000
set cindent
set tabstop=2 " By default 4 indent spaces
set shiftwidth=2 " By default 4 indent spaces
set number " linenumber
set shiftround
set expandtab
set autoindent
set title
set scrolloff=4 " Keep 4 lines above and below cursor
set laststatus=2

set smarttab
set ruler
set hlsearch " highlight results of a search



" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1

" Use compact syntax for prettified multi-line comments
let g:NERDCompactSexyComs = 1

" Align line-wise comment delimiters flush left instead of following code  indentation
let g:NERDDefaultAlign = 'left'

" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1" Enable trimming of trailing whitespace


" TODO do some fugitive config

syntax enable
colorscheme monokai


filetype plugin on
set omnifunc=syntaxcomplete#Complete

"Avoid enter in Replace mode from a double <Insert>
imap <Insert> <Nop>
