icons_format = "{icon}"

[theme]
theme = "nord-dark"

[icons]
icons = "awesome4"

[[block]]
block = "custom"
command = ''' /usr/local/bin/hamtaro '''
interval = 10

[[block]]
block = "custom"
command = ''' /home/carlos/bin/i3_aws_creds  '''
interval = 60
[[block.click]]
button = "left"
action = "/usr/local/bin/aws sso login"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "$icon $available $percentage"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:Mi)($mem_used_percents.eng(w:2)) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 10
format = "$icon $1m "

[[block]]
block = "docker"
interval = 10
format = "$icon $running/$total"

[[block]]
block = "battery"
interval = 10
format = "$percentage $time"

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%a %d/%m %R')"

